### ISSUE TITLE
Gamemode filters and Time limits

### ISSUE THREAD

**Issue by ChunkyPanda03** [ToasterUwU/Pavlov-Game.ini-Creator#1]
I was wondering if you could add support for adding weapon filters like pistols only, rifles only, knives only, grenades only as well as any others I might be forgetting. Another would be to add time limits so that rounds aren't stuck at just an hour. I own a server and know a little python I could help test it. My problem is that I can't figure out which argument to add to the Map rotation.

**Comment by ToasterUwU** [comment]
Hi, thats actually a good idea, but unfortunately, as far as i know, you cant change the time limit. I'm not sure about the Weapon Restrictions. If you can give me an example how to do that, i will implement it.

Also thanks for reaching out to me, its nice to see that people are using the software and want to improve it.

**Comment by ToasterUwU** [comment]
No answer expected
